#!/usr/bin/env python3
"""Generate a versions.py Epoch entry for a Dart release, from that release's own source.

No binary of that release needs to exist. Everything an Epoch carries is derivable from
source we can fetch by tag:

  hash                  MD5 over the 15 files in tools/make_version.py   (sdk_source.py)
  num_predefined_cids   the length of the expanded CLASS_ID_LIST         (gen_cids.py)
  td_int8_cid           cid of TypedDataInt8ArrayCid, the typed-data anchor
  td_byte_data_view_cid cid of ByteDataViewCid, where the typed-data range ends
  tag layout            the ClassIdTag position/width asserted in raw_object.h

What it does not derive is the per-cluster read grammar. `grammars` is emitted empty, so a
generated epoch refuses to parse until someone has validated it. A profile that claimed
support on the strength of a cid table alone would be the silent mis-parse this project
exists to avoid. The loop is: generate, add to versions.py with grammars filled in from
the closest validated epoch, run `jadart --verify` on a real binary, then keep it only if
every Tier-A gate passes.

    python3 tools/gen_epoch.py --tag 3.11.5
"""
from __future__ import annotations

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from sdk_source import fetch, snapshot_hash, FetchError   # noqa: E402
from gen_cids import cid_names_for_tag                    # noqa: E402


def tag_layout(tag: str):
    """(cid_shift, cid_bits) from the ClassIdTag bitfield in raw_object.h.

    Read it, don't assume it. The field has moved before, and a wrong shift decodes every
    cluster tag to the wrong cid."""
    src = fetch(tag, "raw_object.h").decode("utf-8", "replace")
    m = re.search(r"class ClassIdTag\s*:\s*public\s+BitField<[^,]+,\s*(?:[\w:]+)\s*,\s*"
                  r"([^,]+),\s*([^>]+)>", src)
    if not m:
        return None, None
    def val(expr):
        expr = expr.strip()
        if expr.isdigit():
            return int(expr)
        # e.g. `kHashTagPos + kHashTagSize`. Resolve the named constants from the header.
        names = re.findall(r"\b(k\w+)\b", expr)
        total = 0
        for n in names:
            mm = re.search(rf"static constexpr intptr_t {n}\s*=\s*(\d+)", src)
            if not mm:
                return None
            total += int(mm.group(1))
        return total if names else None
    return val(m.group(1)), val(m.group(2))


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="generate a jadart Epoch from SDK source")
    ap.add_argument("--tag", required=True, help="Dart SDK tag, e.g. 3.11.5")
    args = ap.parse_args(argv)

    try:
        h = snapshot_hash(args.tag)
        names = cid_names_for_tag(args.tag)
    except FetchError as e:
        print(f"gen_epoch: {e}", file=sys.stderr)
        return 2

    by_name = {v: k for k, v in names.items()}
    td8 = by_name.get("TypedDataInt8ArrayCid")
    bdv = by_name.get("ByteDataViewCid")
    shift, bits = tag_layout(args.tag)

    print(f'    # generated by tools/gen_epoch.py from the Dart {args.tag} sources')
    print(f'    "{h}": Epoch(')
    print(f'        name="objectheader-{".".join(args.tag.split(".")[:2])}",')
    print(f'        dart="{args.tag}",')
    if shift is not None and bits is not None:
        print(f'        tag=TagLayout(cid_shift={shift}, cid_bits={bits}, '
              f'canonical_bit=1, immutable_bit=7),')
    else:
        print(f'        # ClassIdTag did not parse out of raw_object.h; verify by hand')
    print(f'        num_predefined_cids={len(names)},')
    print(f'        td_int8_cid={td8}, td_byte_data_view_cid={bdv}, td_stride=4,')
    print(f'        # Empty on purpose. The cluster read grammar is not derivable from')
    print(f'        # source here, so this profile refuses every target until someone has')
    print(f'        # run `jadart --verify` on a real binary and seen the Tier-A gates pass.')
    print(f'        grammars=frozenset(),')
    print(f'        notes="generated from Dart {args.tag}; grammar UNVALIDATED",')
    print(f'    ),')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
